name: test

on: [push]
  # push:
  #   branches:
  #   - master
  #   - develop
  # pull_request:

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      fail-fast: true

    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Forge build
        run: |
          forge --version
          make size
        id: build

      - name: Run Forge tests
        run: |
          make test
        env:
          ETH_RPC_URL: ${{ secrets.ETH_RPC_URL }}
          ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
        id: test
